"""add walletsnapshot table

Revision ID: fa371dc0739f
Revises: 
Create Date: 2025-07-11 14:56:38.522034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa371dc0739f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('profit_factor', sa.NUMERIC(precision=18, scale=8), nullable=False),
    sa.Column('expectancy', sa.NUMERIC(precision=18, scale=8), nullable=False),
    sa.Column('risk_reward', sa.NUMERIC(precision=18, scale=8), nullable=False),
    sa.Column('winrate_pct', sa.NUMERIC(precision=6, scale=2), nullable=False),
    sa.Column('net_pnl_30d_usd', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('median_liquidity_usd', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('hhi', sa.NUMERIC(precision=10, scale=6), nullable=False),
    sa.Column('honeypot_share_pct', sa.NUMERIC(precision=6, scale=2), nullable=False),
    sa.Column('days_idle', sa.NUMERIC(precision=8, scale=2), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('avg_hold_human', sa.String(length=32), nullable=False),
    sa.Column('avg_interval_human', sa.String(length=32), nullable=False),
    sa.Column('turnover_usd', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('pnl_per_turnover', sa.NUMERIC(precision=12, scale=6), nullable=False),
    sa.Column('pnl', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', 'ts_utc', name='uix_address_day')
    )
    op.create_index(op.f('ix_wallet_snapshot_address'), 'wallet_snapshot', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_snapshot_address'), table_name='wallet_snapshot')
    op.drop_table('wallet_snapshot')
    # ### end Alembic commands ###
